---

- name: set selinux to allow sshd_admin
  become: yes
  seboolean:
    name: nis_enabled
    state: yes
    persistent: yes

- name: Install sshd_admin.service
  become: yes
  template:
    src: sshd_admin.service.j2
    dest: /usr/lib/systemd/system/sshd_admin.service
    owner: root
    group: root
    mode: 0644
    backup: true

- name: Install base_sshd-admin_config
  become: yes
  template: 
    src: sshd_admin_config.j2
    dest: /etc/ssh/sshd_admin_config
    owner: root 
    group: root 
    backup: true
  notify: Restart SSHD_ADMIN

- name: Add SSHD_ADMIN to firewalld services list
  become: yes
  template: 
    src: sshd_admin.xml.j2
    dest: /etc/firewalld/services/sshd_admin.xml
    owner: root 
    group: root 
    mode: 0644
    backup: true
  notify: Reload FIREWALLD

- meta: flush_handlers
  
- name: Add SSHD_ADMIN to firewalld
  become: yes
  firewalld:
    source: 192.249.7.25/32
    service: sshd_admin
    permanent: true
    state: enabled
    zone: dmz
  notify: Reload FIREWALLD

- name: SSHD_ADMIN
  service:
    name: sshd_admin
    enabled: yes
    state: started
  become: yes

