---
- name: Install Prebuilt Duo
  when: build_duo == false
  block:
  - name: Add Duo Key
    apt_key: 
      url: "https://duo.com/DUO-GPG-PUBLIC-KEY.asc"
      state: present

  - name: Add Duo Source
    copy: 
      src: duosecurity.list 
      dest: "/etc/apt/sources.list.d/duosecurity.list"

  - name: Install Duo Unix SSH Integration
    apt: 
      name: duo-unix 
      state: present 
      update_cache: yes

  - name: Install Duo config
    become: yes
    template: 
      src: pam_duo.conf.j2 
      dest: /etc/duo/pam_duo.conf 
      owner: sshd 
      group: 0 
      mode: 0600

#  - name: Enable duo security for remote logins
#    lineinfile: dest=/etc/ssh/sshd_config regexp=^ForceCommand line="ForceCommand /usr/sbin/login_duo"
#    notify:
#    - restart sshd

- name: Install Duo Unix SSH Integration build-it
  when: build_duo == true
  block:
  - name: Install Prerequisites
    become: yes
    apt:
      state: present
      update_cache: yes
      pkg:
      - myproxy
      - gcc
      - make
      - autoconf
      - libtool
      - libssl-dev
      - libpam-dev

  - name: Clone duo_unix source
    ansible.builtin.git:
      repo: https://github.com/duosecurity/duo_unix.git
      dest: /tmp/duo_unix
      single_branch: yes
      version: master

  - name: Boostrapping duo_unix source
    command: "./bootstrap"
    args:
      chdir: "/tmp/duo_unix"

  - name: Configuring duo_unix source
    command: "./configure --prefix=/usr --with-pam"
    args:
      chdir: "/tmp/duo_unix"
    register: duo_configure

  - name: Installing freshly built duo
    become: yes
    shell: make && make install
    args:
      chdir: "/tmp/duo_unix"
      #chdir: "/tmp/{{ xsede_duo_version }}"
#  when: duo_configure|changed

  - name: Install Duo config
    become: yes
    template: 
      src: pam_duo.conf.j2 
      dest: /etc/duo/pam_duo.conf 
      owner: sshd 
      group: 0 
      mode: 0600
