---

- name: Base playbook
  import_playbook: base.yml

- name: A3M_DEV
  hosts: tag_Name_a3m_dev
  gather_facts: yes
  roles:
    - { role: git, tags: git}

- name: A3M_PROD
  hosts: tag_Name_a3m_prod
  gather_facts: yes
  roles:
    - { role: git, tags: git}
    - { role: cron, tags: cron}
    - { role: postgres, tags: postgres}
    - { role: hostname, tags: hostname}
