---
- hosts: tag_cm_ansible
  gather_facts: yes
  roles:
    - { role: admin_accounts, tags: admin_accounts}
    - { role: sshd, tags: [ "sshd", "ssh", "authentication" ] }
    - { role: sshd_admin, tags: [ "sshd", "ssh", "authentication" ] }
    - { role: pw, tags: [ "pw", "authentication" ] }
    - { role: pam, tags: [ "pam", "authentication" ] }
    - { role: syslog, tags: syslog }
    - { role: fail2ban, tags: [ "fail2ban", "network" ] }
    - { role: rsa, tags: [ "rsa", "authentication" ] }
    - { role: sudo, tags: [ "sudo", "authentication" ] }
    - { role: firewalld, tags: [ "firewalld", "network" ] }
    - { role: postfix, tags: postfix }
    - { role: chronyd, tags: chronyd }
