---
- name: Implement client main.cf
  become: yes
  template:
    src: client_main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
   restart_postfix

- name: Create mailarchive user
  become: yes
  user:
    name: mailarchive
    comment: Mail Archive
    shell: /sbin/nologin
    createhome: no
    home: /var/archive/mail

- name: Create mailarchive homedir
  become: yes
  file:
    path: "{{ item.dir }}"
    state: directory
    mode: 0755
    owner: nobody
    group: nobody
  with_items:
    - { dir: '/var/archive'}
    - { dir: '/var/archive/mail/tmp'}
    - { dir: '/var/archive/mail/cur'}
    - { dir: '/var/archive/mail/new'}

- name: Update aliases
  become: yes
  lineinfile: 
    path: /etc/aliases
    line: 'mailarchive: /var/archive/mail/'
  notify:
    newaliases
