---

- name: Add groups (var- groups_list)
  become: yes
  group: 
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{groups_list}}"

- name: Add accounts (var- users_list)
  become: yes
  user: 
    name: "{{ item.name }}"
    comment: "{{ item.common }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    create_home: yes
    append: no
    skeleton: "/etc/skel"
  with_items:
    - "{{users_list}}"
