---
- name: Stop FAIL2BAN
  service: 
    name=fail2ban 
    state=stopped
  become: yes

- name: Start FAIL2BAN
  service: 
    name=fail2ban 
    state=started
  become: yes

- name: Restart FAIL2BAN
  service: 
    name=fail2ban 
    state=restarted
  become: yes
