---
- name: Copy PAM.D sshd config
  become: yes
  template:
    src: sshd.j2
    dest: /etc/pam.d/sshd
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Copy PAM.D sudo config
  become: yes
  template:
    src: sudo.j2
    dest: /etc/pam.d/sudo
    owner: root
    group: root
    mode: 0644
    backup: yes

