---
- name: Restart FIREWALLD
  service: 
    name= "{{ item.name }}"
    state= "{{ item.state}}"
  with_items:
    - " {{ name: firewalld, state: restarted }}"
    - " {{ name: fail2ban, state: restarted }}"
  become: yes

- name: Reload FIREWALLD
  command: "{{ item }}"
  with_items: 
    - firewall-cmd --reload
    - systemctl reload fail2ban
  become: yes
