---

- name: Install cronjob
  become: yes
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    user: "{{ item.user }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    day: "{{ item.day }}"
    month: "{{ item.month }}"
    weekday: "{{ item.weekday }}"
    state: "{{ item.state }}"
  with_items:
    - "{{cron_jobs}}"

- name: Create cron dir
  become: yes
  file:
    path: "{{ item.root }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    recurse: yes
    state: directory
  with_items:
    - "{{cron_files}}"
    

- name: Copy cron files
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.root }}/{{ item.dest }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: yes
  with_items:
    - "{{cron_files}}"
  
