---
- name: Stop RSYSLOG
  service: name=rsyslog state=stopped
  become: yes

- name: Start RSYSLOG
  service: name=rsyslog state=started
  become: yes

- name: Restart RSYSLOG
  service: name=rsyslog state=restarted
  become: yes
