---

- name: install chronyd
  become: yes
  package:
    name: chrony
    state: present

- name: enable service
  become: yes
  service:
    name: chronyd
    enabled: yes
    state: started

- name: Set timezone link
  become: yes
  file:
    src: /usr/share/zoneinfo/UTC
    dest: /etc/localtime
    owner: root
    group: root
    state: link


