---
# Which template file should be used
sshd_template_file: 'sshd_config.j2'

# Variables used in the template
#
# Note: sshd_allowusers and sshd_server_ops_staff are concantinated in the sshd_config.j2 template
sshd_allowusers:
sshd_authenticationmethods: 'publickey,keyboard-interactive'
sshd_server_ops_staff: 'ansible'

sshd_protocol: 2
sshd_port: 22
sshd_useprivilegeseparation: 'yes'
sshd_hostkey: 
  - '/etc/ssh/ssh_host_rsa_key'
  - '/etc/ssh/ssh_host_ecdsa_key'
sshd_loglevel: 'INFO'
sshd_syslogfacility: 'AUTHPRIV'
sshd_rsaauthentication: 'no'
sshd_permitrootlogin: 'no'
sshd_passwordauthentication: 'no'
sshd_hostbasedauthentication: 'no'
sshd_ignoreuserknownhosts: 'no'
sshd_ignorerhosts: 'yes'
sshd_challengeresponseauthentication: 'yes'
sshd_usepam: 'yes'
sshd_acceptenv: 
  - 'LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES'
  - 'LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT'
  - 'LC_IDENTIFICATION LC_ALL'
sshd_x11forwarding: 'no'
sshd_x11uselocalhost: 'no'
sshd_xauthlocation: '/usr/bin/xauth'
sshd_clientaliveinterval: 600
sshd_clientalivecountmax: 3
sshd_banner: '/etc/banner/sshd.banner'
sshd_subsystem: 'sftp    /usr/libexec/openssh/sftp-server'
sshd_denyusers: 'apache www-data'
sshd_pubkeyauthentication: 'yes'
sshd_matchusers: "Match User ubuntu\n\tPubKeyAuthentication yes\n\tAuthenticationMethods publickey"
