---
- name: install fail2ban
  become: yes
  package:
    name: fail2ban
    state: present

- service: 
    name: fail2ban
    enabled: yes
    state: started
  become: yes

- name: Install jail_local
  become: yes
  template: 
    src: jail.local.j2 
    dest: /etc/fail2ban/jail.local 
    owner: root 
    group: root 
    backup: true
  notify: Restart FAIL2BAN

- name: Install iptables-common.conf
  become: yes
  template: 
    src: iptables-common.conf.j2 
    dest: /etc/fail2ban/action.d/iptables-common.conf 
    owner: root 
    group: root 
    backup: true
  notify: Restart FAIL2BAN

- name: Install jail.conf filter
  become: yes
  template:
    src: jail.conf.j2
    dest: /etc/fail2ban/jail.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: Restart FAIL2BAN

- name: Install gsisshd filter
  become: yes
  template:
    src: gsisshd.conf.j2
    dest: /etc/fail2ban/filter.d/gsisshd.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: Restart FAIL2BAN
  when: gsisshd_fail2ban is defined
