---
- name: Install firewalld rpm
  apt:
    name: firewalld
    state: present
  become: yes

- service:
    name: firewalld
    enabled: yes
    state: started
  become: yes

- name: Set DMZ to be default zone
  become: yes
  command: firewall-cmd --set-default-zone=dmz
  changed_when: False

- name: Install direct rules xml from template
  become: yes
  template: 
    src: direct.xml.j2 
    dest: /etc/firewalld/direct.xml 
    owner: root 
    group: root 
    mode: 0640
  notify: Reload FIREWALLD

- block:
  - name: Change firewall zones on an interface
    firewalld:
      zone: "{{ item.zone }}"
      interface: "{{ item.interface }}"
      permanent: "{{ item.permanent }}"
      state: "{{ item.state }}"
    with_items: "{{ firewalld_config_zone }}"
    notify: Reload FIREWALLD
    when: item.source == "false" and item.service == "false"

  - name: Change firewall zones on a source network
    firewalld:
      zone: "{{ item.zone }}"
      source: "{{ item.source }}"
      permanent: "{{ item.permanent }}"
      state: "{{ item.state }}"
    with_items: "{{ firewalld_config_zone }}"
    notify: Reload FIREWALLD
    when: item.interface == "false" and item.service == "false"

  - name: Change services in a zone
    firewalld:
      zone: "{{ item.zone }}"
      service: "{{ item.service }}"
      permanent: "{{ item.permanent }}"
      state: "{{ item.state }}"
    with_items: "{{ firewalld_config_zone }}"
    notify: Reload FIREWALLD
    when: item.interface == "false" and item.source == "false"

  become: true
  when: firewalld_config_zone is defined
