- hosts: search-pilot.operations.access-ci.org
  gather_facts: yes
  become: true
  become_user: root

  vars:
    enable_selinux: false

  tasks:
    - include_vars: passwords.yml

    - include_tasks: application.yml
