- name: Install distribution software
  apt:
    state: present
    pkg:
      - nginx
      - libpq-dev
      - postgresql-client-common
      - postgresql-client-14

# Must run to set Python facts needed for subsequent configurations
- include_tasks: python3_native.yml

# Must run to set facts needed for subsequent configurations
- include_vars: dgpf1_vars.yml

- include_tasks: letsencrypt.yml

  #- include_tasks: nginx.yml

  #- include_tasks: dgpf1_code.yml

  #- include_tasks: dgpf1.yml
