---
- name: Stop SSHD
  service:
    name: sshd 
    state: stopped
  become: yes

- name: Start SSHD
  service: 
    name: sshd
    state: started
  become: yes

- name: Restart SSHD
  service: 
    name: sshd
    state: restarted
  become: yes
