---
- name: Copy RSA libs 64
  become: yes
  copy:
    src: pam/lib/64bit/pam_securid.so
    dest: /lib64/security/pam_securid.so
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Setup ACE directory
  become: yes
  file: path=/var/ace/ state=directory

- name: Copy failover.dat binaries
  become: yes
  copy:
    src: xsede/failover.dat
    dest: /var/ace/failover.dat
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Copy sdconf.rec binaries
  become: yes
  copy:
    src: xsede/sdconf.rec
    dest: /var/ace/sdconf.rec
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Setup PAM directory
  become: yes
  file: path=/opt/pam/ state=directory

- name: Copy PAM binary acestatus
  become: yes
  copy:
    src: pam/bin/64bit/acestatus
    dest: /opt/pam/acestatus
    owner: root
    group: root
    mode: 0700
    backup: yes

- name: Copy PAM binary acetest
  become: yes
  copy:
    src: pam/bin/64bit/acetest
    dest: /opt/pam/acetest
    owner: root
    group: root
    mode: 0700
    backup: yes

- name: Copy PAM binary ns_conv_util
  become: yes
  copy:
    src: pam/bin/64bit/ns_conv_util
    dest: /opt/pam/ns_conv_util
    owner: root
    group: root
    mode: 0700
    backup: yes

- name: Copy sd_pam.conf
  become: yes
  copy:
    src: sd_pam.conf
    dest: /etc/sd_pam.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Verify secret node file reinstalling machine
  local_action: stat path=roles/rsa/hosts/securid2/{{ ec2_tag_Name }}.securid2
  register: file
  ignore_errors: True

- name: Copy secret node file
  become: yes
  copy:
    src: roles/rsa/hosts/securid2/{{ ec2_tag_Name }}.securid2
    dest: /var/ace/securid2
    owner: root
    group: root
    mode: 0400
    backup: yes
  when: file.stat.exists

- name: Fetch node file after initial install, copy secret node file
  become: yes
  fetch:
    src: /var/ace/securid2
    dest: roles/rsa/hosts/securid2/{{ ec2_tag_Name }}.securid2
    flat: yes
  when: file.stat.exists == False

- name: Generate sdopts.rec for amazon hosts
  become: yes
  template:
    src: sdopts_rec.j2
    dest: /var/ace/sdopts.rec
    owner: root
    group: root
